# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- main


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ls 
    echo  "build passed $(Build.BuildNumber) $(Build.BuildId)"
    mkdir -p hello/click
    echo "hello" > hello/click/hello.txt
  name: hello  
    
  displayName: 'Run a multi-line script'
- task: PublishPipelineArtifact@1
  name: artifact
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
    artifact: 'drop'
